import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string, defaultVal?: string): Promise<string> {
  const prompt = defaultVal ? `${question} [${defaultVal}]: ` : `${question}: `;
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

function print(msg: string) {
  console.log(msg);
}

const SOUL_TEMPLATE = `# Babu Bhai

You are Babu Bhai, a senior full-stack developer and DevOps engineer.
You speak concisely and prefer action over discussion.
You always explain your reasoning before making changes.
You never commit without asking first.

## Rules
- Always read the file before editing
- Use conventional commits
- Prefer small, focused changes
- Run tests after code changes
- Be helpful but direct
`;

const IDENTITY_TEMPLATE = `# Identity

name: Babu Bhai
role: AI Development Agent
channel: Telegram
version: 0.1.0
`;

export async function runSetupWizard(): Promise<void> {
  print("");
  print("╔══════════════════════════════════════╗");
  print("║       🤖 Babu Bhai Setup Wizard      ║");
  print("╚══════════════════════════════════════╝");
  print("");

  // Step 1: Telegram Bot
  print("── Step 1: Telegram Bot ──");
  print("Create a bot via @BotFather in Telegram (send /newbot)");
  print("");

  const botToken = await ask("Paste your Telegram bot token");
  if (!botToken || !botToken.includes(":")) {
    print("❌ Invalid bot token. Must contain ':'. Run setup again.");
    rl.close();
    process.exit(1);
  }

  const botUsername = await ask("Bot username (without @)");
  if (!botUsername) {
    print("❌ Bot username is required. Run setup again.");
    rl.close();
    process.exit(1);
  }

  // Step 2: Your Telegram ID
  print("");
  print("── Step 2: Your Telegram ID ──");
  print("Message @userinfobot on Telegram to get your ID");
  print("");

  const allowedUsers = await ask("Your Telegram user ID(s), comma-separated");
  if (!allowedUsers || !/^\d+(,\d+)*$/.test(allowedUsers.replace(/\s/g, ""))) {
    print("❌ At least one numeric Telegram user ID is required.");
    rl.close();
    process.exit(1);
  }

  // Step 3: Project Directory
  print("");
  print("── Step 3: Project Directory ──");
  print("The directory the bot can access (your code projects)");
  print("");

  const approvedDir = await ask("Approved directory path", process.env.HOME ?? "/home");
  if (!existsSync(approvedDir)) {
    print(`❌ Directory does not exist: ${approvedDir}`);
    rl.close();
    process.exit(1);
  }

  // Step 4: Claude Model
  print("");
  print("── Step 4: Claude Model ──");
  print("Options: claude-sonnet-4-6, claude-opus-4-6, claude-haiku-4-5");
  print("");

  const model = await ask("Claude model", "claude-sonnet-4-6");

  // Step 5: Caveman Mode
  print("");
  print("── Step 5: Token Savings (Caveman) ──");
  print("Reduces output tokens by 60-75% with terse responses.");
  print("Modes: off, lite (40%), full (65%), ultra (75%)");
  print("");

  const cavemanMode = await ask("Default caveman mode", "full");

  // Step 6: Bot Personality
  print("");
  print("── Step 6: Bot Personality ──");
  print("Give your bot a personality via SOUL.md (you can edit later)");
  print("");

  const botName = await ask("Bot display name", "Babu Bhai");
  const customSoul = await ask("Use default personality? (y/n)", "y");

  // Step 7: Max turns and timeout
  print("");
  print("── Step 7: Limits ──");
  const maxTurns = await ask("Max tool-use turns per message", "10");
  const timeout = await ask("Timeout per message (seconds)", "300");
  const rateLimit = await ask("Max messages per minute per user", "10");

  // Write .env
  print("");
  print("── Writing configuration... ──");

  const envContent = [
    `# Babu Bhai Configuration`,
    `# Generated by setup wizard on ${new Date().toISOString()}`,
    ``,
    `# Telegram`,
    `TELEGRAM_BOT_TOKEN=${botToken}`,
    `TELEGRAM_BOT_USERNAME=${botUsername}`,
    ``,
    `# Security`,
    `ALLOWED_USERS=${allowedUsers.replace(/\s/g, "")}`,
    `APPROVED_DIRECTORY=${approvedDir}`,
    ``,
    `# Claude`,
    `CLAUDE_MODEL=${model}`,
    `CLAUDE_MAX_TURNS=${maxTurns}`,
    `CLAUDE_TIMEOUT_SECONDS=${timeout}`,
    ``,
    `# Features`,
    `AGENTIC_MODE=true`,
    `ENABLE_MEMORY=true`,
    `CAVEMAN_MODE=${cavemanMode}`,
    `LOG_LEVEL=info`,
    ``,
    `# Rate Limiting`,
    `RATE_LIMIT_REQUESTS=${rateLimit}`,
    `RATE_LIMIT_WINDOW_MS=60000`,
  ].join("\n");

  const projectRoot = resolve(import.meta.dir, "..", "..");
  writeFileSync(resolve(projectRoot, ".env"), envContent);
  print("✅ .env written");

  // Write identity files
  const configDir = resolve(approvedDir, ".babu-bhai");
  mkdirSync(resolve(configDir, "memory"), { recursive: true });

  const soul =
    customSoul.toLowerCase() === "n"
      ? `# ${botName}\n\nCustomize this file with your bot's personality.\n`
      : SOUL_TEMPLATE.replace(/Babu Bhai/g, botName);

  const identity = IDENTITY_TEMPLATE.replace(/Babu Bhai/g, botName);

  writeFileSync(resolve(configDir, "SOUL.md"), soul);
  writeFileSync(resolve(configDir, "IDENTITY.md"), identity);
  print("✅ SOUL.md and IDENTITY.md written");

  // Done
  print("");
  print("╔══════════════════════════════════════╗");
  print("║         ✅ Setup Complete!            ║");
  print("╚══════════════════════════════════════╝");
  print("");
  print("Start the bot:");
  print("  bun start");
  print("");
  print("Or in dev mode (auto-reload):");
  print("  bun dev");
  print("");
  print(`Then message @${botUsername} on Telegram!`);
  print("");
  print("Files created:");
  print(`  .env                        — Bot configuration`);
  print(`  ${configDir}/SOUL.md        — Bot personality`);
  print(`  ${configDir}/IDENTITY.md    — Bot metadata`);
  print("");

  rl.close();
}

// Run if called directly
if (import.meta.main) {
  runSetupWizard().catch((e) => {
    console.error("Setup failed:", e);
    process.exit(1);
  });
}
